### ISSUE TITLE
I do not have access to "https://bitbucket.org/gentu/vendor_zte_nx503a"

### ISSUE THREAD

**Issue by rjlee0** [gentu/android_vendor_zte_nx503a#2]
Hi, @gentu 
I do not have access to "https://bitbucket.org/gentu/vendor_zte_nx503a"
How can I sync it.

**Comment by gentu** [comment]
Hi!
I will publish vendor tree and updated source code in the next few days.

**Comment by gentu** [comment]
I released updated source code. But now I stop work on CyanogenMod for the ZTE Nubia Z5S.
